version: 2.1
orbs:
  aws-cli: circleci/aws-cli@3.1

commands:
  set-npm-registry:
    steps:
      - run:
          name: Set npm registry
          command: |
            echo "registry=https://registry.npmjs.org/" >> ./.npmrc
            echo "@animaapp:registry=https://npm.pkg.github.com" >> ./.npmrc
            echo "//npm.pkg.github.com/:_authToken=${GITHUB_PACKAGE_TOKEN}" >> ./.npmrc
            echo "always-auth=true" >> ./.npmrc

workflows:
  storybook-cli:
    jobs:
      - build-and-test:
          context: 
            - anima-prod
            - AWS
      - docs-publish:
          context: 
            - anima-prod
            - AWS
          requires:
            - build-and-test
          filters:
            branches:
              only: docs/init-docs         
  storybook-cli-nightly-test:
    triggers:
      - schedule:
          cron: "0 3 * * *"
          filters:
            branches:
              only: master 
    jobs:
      - build-and-test:
          context:
            - anima-prod
            - AWS  

jobs:
  build-and-test:
    docker:
      - image: node:16
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: default
      - set-npm-registry
      - run:
          name: "Install Ubuntu dependencies"
          command: |
            apt-get -y update
            apt-get install -y jq
      - run:
          name: 'Install pnpm'
          command: 'npm i -g pnpm@latest'
      - run:
          name: "Install dependencies"
          command: "pnpm i"
      - run:
          name: "Build"
          command: "pnpm build"
      - run:
          name: "Run e2e tests"
          command: "pnpm test"
      - persist_to_workspace:
          root: .
          paths:
            - packages/docs/.vitepress/dist

  docs-publish:
    docker:
      - image: cimg/base:stable
    steps:
      - attach_workspace:
          at: .
      - aws-cli/setup:
          profile-name: default
      - run:
          name: Upload to S3
          command: |
            aws s3 sync packages/docs/.vitepress/dist s3://anima-dsa-docs/ --delete

