name: Build and test
on:
  push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.yarnpkg.com'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        aws-region: us-west-2
      - name: Install dependencies and build 🔧
        run: yarn install && npm run build
      - name: Tests
        run: yarn test
        env:
          TEST_TOKEN: ${{ secrets.TEST_TOKEN }}
