name: Publish to NPM
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.yarnpkg.com'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_PACKAGE_TOKEN: ${{ secrets.GH_PACKAGE_TOKEN }}
      - name: Creating .npmrc
        run: |
          cat << EOF > "./.npmrc"
           registry=https://registry.npmjs.org/
           @animaapp:registry=https://npm.pkg.github.com
           //npm.pkg.github.com/:_authToken=$GH_PACKAGE_TOKEN
           //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
          EOF
      - name: Install dependencies and build 🔧
        run: npm i -g pnpm && pnpm i && pnpm build
      - name: Publish package on NPM 📦
        run: pnpm publish --filter "@animaapp/framework-helpers" --filter "anima-storybook-cli" --no-git-checks --access=public
